# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.27
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: false
enable_checklog_odoo: true
generate_requirements_txt: false
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 18.0
org_name: bealdav
org_slug: bealdav
rebel_module_groups: []
repo_description: Define transitory fields
repo_name: odoo-migration-field
repo_slug: odoo-migration-field
repo_website: https://github.com/bealdav/odoo-migration-field
use_pyproject_toml: true
use_ruff: true

